spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=chat_messages;encrypt=true;trustServerCertificate=true;
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 9090